### ISSUE TITLE
Check touch doesn't work - homework 5

### ISSUE THREAD

**Issue by noemi-antonia** [noemi-antonia/music-app#1]

**Comment by vanceacorina97** [comment]
Hi Noemi, the touch from homework 5 doesn't work because:
1. You didn't calculate `width` and `height` depending on the canvas ( you need these to be able to determinate the position of each answer, after that you can stylize it, it will automatically calculate after :smile: )
2. `if (a.classList.contains('answer') && p.y < bBox.y - origins.y + 100) {
          activate = false;
        }` it will enter here every time even if it is initially activated. Also, you don't even need this piece of code. 
3. In the `drawHand` method you calculated "hardcoded" the distance between the points, so it will claim that they are/ are not always active.
4. I also solved your problem and added a pull request on your repository :smile:
